name: Tags Main Pipeline

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "*"

jobs:
  run-badges:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: trigger bagdes
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: badges-workflow