name: Main pipeline

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write

run-name: ${{ github.event.commits[0].message }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/*
  pull_request:
  repository_dispatch:
    types: [badges-workflow]

jobs:
  run-badges:
    uses: ./.github/workflows/badge-generator.yaml
    with:
      ref-name: pythonImage
      coverage: "90.2"
      flake8-issues: "2"
      mypy-score: "80.1"